configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGVkYzBiZmJiMmQ5OWYzNTg1NWYyOGNkMzA1ZjVkOGQ5NzA4OTNlYzI0NGZiMTFiZjU5YWMzYTg5YmYzMDI4ZjhhNjVhMTM0MTYzMTUzOGY3NDgyZmNmZDM1MWRhYTM1ZTg1MzAwYzJhNmE4NTQ1OTFiNjJkMDI4ZjM0ZDg5YzU=
